export const FETCH_FILE = 'FETCH_FILE';
export const FETCH_FILE_FAILED = 'FETCH_FILE_FAILED';
export const SORT_INCOME = 'SORT_INCOME';
export const EDIT_INCOME = 'EDIT_INCOME';
export const SET_ACCOUNT_STATE = 'SET_ACCOUNT_STATE';

export const LOADING_START = "LOADING_START";
export const LOADING_END = "LOADING_END";

export const ASSIGN_INCOME_BY_CODE = "ASSIGN_INCOME_BY_CODE";

