
export const teamsMap = [
  { 'teamId': '1111', 'name': 'CYWILE' },
  { 'teamId': '6673', 'name': '4 Harcerska Drużyna Wodna "HOOK"', 'nameToUse': '4 Harcerskiej Drużyny Wodnej "HOOK"' },
  { 'teamId': '6676', 'name': 'III RMŚSzDZHShiW "Pomarańczowe Jedynki"', 'nameToUse': 'III RMŚSzDZHShiW "Pomarańczowe Jedynki"' },
  { 'teamId': '6682', 'name': '17 Rudzka Grunwaldzka Drużyna Harcerska "Victory"', 'nameToUse': '17 Rudzkiej Grunwaldzkiej Drużyny Harcerskiej "Victory"' },
  { 'teamId': '6689', 'name': '7 Rudzka Drużyna Harcerska "Albatrosy"', 'nameToUse': '7 Rudzkiej Drużyny Harcerskiej "Albatrosy"' },
  { 'teamId': '6692', 'name': '1 Rudzka Środowiskowa Gromada Zuchowa "Przyjaciele Zielonego Lasu"', 'nameToUse': '1 Rudzkiej Środowiskowej Gromady Zuchowej "Przyjaciele Zielonego Lasu"' },
  { 'teamId': '6693', 'name': '3 Rudzka Gromada Zuchowa NS', 'nameToUse': '3 Rudzkiej Gromady Zuchowej NS' },
  { 'teamId': '6697', 'name': '1 Rudzka Środowiskowa Drużyna Harcerska "Młode wilki"', 'nameToUse': '1 Rudzkiej Środowiskowej Drużyny Harcerskiej "Młode wilki"' },
  { 'teamId': '6698', 'name': 'I Szczep "Prima"', 'nameToUse': 'I Szczepu "Prima"' },
  { 'teamId': '6699', 'name': '1 Rudzka Środowiskowa Drużyna Wędrownicza "ZWiW', 'nameToUse': '1 Rudzkiej Środowiskowej Drużyny Wędrownicze "ZWiW"' },
  { 'teamId': '6700', 'name': '101 Rudzka Specjalnościowa Drużyna Wędrownicza "Rose\'s team"', 'nameToUse': '101 Rudzkiej Specjalnościowej Drużyny Wędrowniczej "Rose\'s team"' },
  { 'teamId': '6701', 'name': '11 Rudzka Drużyna Harcerska', 'nameToUse': '11 Rudzkiej Drużyny Harcerskiej' },
  { 'teamId': '6704', 'name': '13 Rudzka Drużyna Harcerska', 'nameToUse': '13 Rudzkiej Drużyny Harcerskiej' },
  { 'teamId': '6705', 'name': '2 Rudzka Grunwaldzka Drużyna Harcerska', 'nameToUse': '2 Rudzkiej Grunwaldzkiej Drużyny Harcerskiej' },
  { 'teamId': '6706', 'name': '3 Rudzka Drużyna Starszoharcerska NS', 'nameToUse': '3 Rudzkiej Drużyny Starszoharcerskiej NS' },
  { 'teamId': '6707', 'name': '77 Rudzka Grunwaldzka Drużyna Harcerska "Twierdza"', 'nameToUse': '77 Rudzkiej Grunwaldzkiej Drużyny Harcerskiej "Twierdza"' },
  { 'teamId': '6711', 'name': '90 Rudzka Środowiskowa Grunwaldzka Drużyna Harcerska "Indianie"', 'nameToUse': '90 Rudzkiej Środowiskowej Grunwaldzkiej Drużyny Harcerskiej "Indianie"' },
  { 'teamId': '6713', 'name': '3 Rudzka Drużyna Harcerska NS', 'nameToUse': '3 Rudzkiej Drużyny Harcerskiej NS' },
  { 'teamId': '6717', 'name': '55 Rudzka Drużyna Harcerska "Rara avis"', 'nameToUse': '55 Rudzkiej Drużyny Harcerskiej "Rara avis"' },
  { 'teamId': '6722', 'name': '11 Rudzka Gromada Zuchowa "Strażnicy żywiołów', 'nameToUse': '11 Rudzkiej Gromady Zuchowej "Strażnicy żywiołów'},
  { 'teamId': '6723', 'name': '27 Rudzka Drużyna Harcerska "Madagaskar"', 'nameToUse': '27 Rudzkiej Drużyny Harcerskiej "Madagaskar"' },
  { 'teamId': '11600', 'name': '44 Rudzka Drużyna Harcerska "RAPS"', 'nameToUse': '44 Rudzkiej Drużyny Harcerskiej "RAPS"' },
  { 'teamId': '12427', 'name': '111 Rudzka Drużyna Harcerska "Signum temporis"', 'nameToUse': '111 Rudzkiej Drużyny Harcerskiej "Signum temporis"' },
  { 'teamId': '14149', 'name': '55 Rudzka Gromada Zuchowa "Pracowite pszczółki"', 'nameToUse': '55 Rudzkiej Gromady Zuchowej "Pracowite pszczółki"' },
  { 'teamId': '15439', 'name': 'SENIORZY', 'nameToUse': 'seniorów' },
  { 'teamId': '15446', 'name': '1 Rudzka Drużyna Starszoharcerska "Wind rose"', 'nameToUse': '1 Rudzkiej Drużyny Starszoharcerskiej "Wind rose"' },
  { 'teamId': '15946', 'name': '2 Rudzka Gromada Zuchowa "Sprytne liski"', 'nameToUse': '2 Rudzkiej Gromady Zuchowej "Sprytne liski"' },
  { 'teamId': '15947', 'name': '90 Rudzka Gromada Zuchowa "Orle pióro"', 'nameToUse': '90 Rudzkiej Gromady Zuchowej "Orle pióro"' },
  { 'teamId': '15948', 'name': '6 Rudzka Drużyna Harcerska', 'nameToUse': '6 Rudzkiej Drużyny Harcerskiej' },
  { 'teamId': '17203', 'name': '79 Drużyna Harcerska w Przyszowicach', 'nameToUse': '79 Drużyny Harcerskiej w Przyszowicach' },
  { 'teamId': '17905', 'name': 'NS', 'nameToUse': 'NS' },
  { 'teamId': '110202', 'name': 'HUFIEC', 'nameToUse': 'Hufca ZHP w Rudzie Śląskiej' },
].sort((a, b) => Number(a.teamId) - Number(b.teamId));

// export const teamsMap = [
//   { "teamId": "1111", "name": "CYWILE" },
// 	 { "teamId": "6673", "name": "4 HDW" },
// 	 { "teamId": "6676", "name": "III Szczep 'Pomarańczowe Jedynki'" },
// 	 { "teamId": "6682", "name": "17 Rudzka Grunwaldzka Drużyna Harcerska" },
// 	 { "teamId": "6689", "name": "7 Rudzka Drużyna Harcerska" },
// 	 { "teamId": "6692", "name": "1 RŚGZ" },
// 	 { "teamId": "6692", "name": "3 Rudzka Gromada Zuchowa NS" },
// 	 { "teamId": "6697", "name": "1 RŚDH" },
// 	 { "teamId": "6698", "name": "I Szczep 'Prima'" },
// 	 { "teamId": "6699", "name": "1 RŚDW" },
// 	 { "teamId": "6700", "name": "101 RSDW" },
// 	 { "teamId": "6701", "name": "11 Rudzka Drużyna Harcerska" },
// 	 { "teamId": "6704", "name": "13 Rudzka Drużyna Harcerska" },
// 	 { "teamId": "6705", "name": "2 Rudzka Grunwaldzka Drużyna Harcerska" },
// 	 { "teamId": "6706", "name": "3 RDS NS" },
// 	 { "teamId": "6707", "name": "77 Rudzka Grunwaldzka Drużyna Harcerska" },
// 	 { "teamId": "6711", "name": "90 RŚGDH" },
// 	 { "teamId": "6713", "name": "3 Rudzka Drużyna Harcerska NS" },
// 	 { "teamId": "6717", "name": "55 Rudzka Drużyna Harcerska" },
// 	 { "teamId": "6722", "name": "11 Rudzka Gromada Zuchowa" },
// 	 { "teamId": "6723", "name": "27 Rudzka Drużyna Harcerska" },
// 	 { "teamId": "11600", "name": "44 Rudzka Drużyna Harcerska" },
// 	 { "teamId": "12427", "name": "111 Rudzka Drużyna Harcerska" },
// 	 { "teamId": "14149", "name": "55 Rudzka Gromada Zuchowa" },
// 	 { "teamId": "15439", "name": "SENIORZY" },
// 	 { "teamId": "15446", "name": "1 RDS" },
// 	 { "teamId": "15946", "name": "2 Rudzka Gromada Zuchowa" },
// 	 { "teamId": "15947", "name": "90 Rudzka Gromada Zuchowa" },
// 	 { "teamId": "15948", "name": "6 Rudzka Drużyna Harcerska" },
// 	 { "teamId": "17203", "name": "79 DH PRZYSZOWICE" },
// 	 { "teamId": "17905", "name": "NS" },
// 	 { "teamId": "110202", "name": "HUFIEC" },
// ];